 resources:
- name: source-code
  type: git
  source:
    uri: https://github.com/jshingler/testConcourseCredhub.git
    branch: master


jobs:
- name: hello-world
  plan:
  - task: say-hello
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: ubuntu}
      run:
        path: echo
        args: ["Hello, world!"]
  - get: source-code
  - task: build-bin
    file: source-code/task.yml
